language: java

jobs:
  include:
    - stage: build
      jdk:
       - oraclejdk8
      script: ./gradlew build
    - stage: test
      jdk:
        - oraclejdk8
        - openjdk8
      script: ./gradlew check

stages:
  - build
  - test
